#       Copyright (c) 1987 AT&T
#         All Rights Reserved

#       THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#       The copyright notice above does not evidence any
#       actual or intended publication of such source code.

# @(#)makefile	1.1.1.10	(6/16/88)

include ../../../stand.defs

TOOLNAME=	dmddemo/lg_demo/life
TC630=		../../../..
SOURCE=		makefile
SUBDIRSHOST=	host
SUBDIRS5620=	$(SUBDIRSHOST) term
SUBDIRS630=	$(SUBDIRS5620)

include ../../../stand.targ
