#       Copyright (c) 1987 AT&T   
#       All Rights Reserved       

#       THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T   
#       The copyright notice above does not evidence any     
#       actual or intended publication of such source code.  

# @(#)makefile	1.1.1.5	(6/16/88)

include ../../stand.defs

TC630=../../..
TOOLNAME=dmddemo/lg_demo
SUBDIRSHOST=life
SUBDIRS5620=$(SUBDIRSHOST) smiley calc
SUBDIRS630=$(SUBDIRS5620)
SOURCE=


include ../../stand.targ
